apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: git-sub-app
  namespace: git-sub-ns-helm
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      name: git-sub