apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: towhichcluster
  namespace: git-sub-ns-helm
  labels:
    name: git-sub
spec:
  clusterSelector:
    matchLabels:
      environment: Dev
  clusterReplicas: 1