apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: git-helm-sub
  namespace: git-sub-ns-helm
  labels:
    name: git-sub
spec:
  channel: ch-git-helm/git-helm
  placement:
    placementRef:
      name: towhichcluster
      kind: PlacementRule