apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortener-deployment
spec:
  selector:
    matchLabels:
      app: urlshortener
  replicas: {{ int .Values.replicas }} # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: urlshortener
        image: quay.io/myan/urlshortener-front
        ports:
        - containerPort: 80
