apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  selector:
    matchLabels:
      app: simple-deployment-app
  replicas: {{ int .Values.replicas }} # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: simple-deployment-app
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
            - sleep
            - "36000"